version: '3.8'

services:
  node1:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - node1_data:/app/data

  node2:
    build: .
    ports:
      - "5002:5000"
    volumes:
      - node2_data:/app/data

  node3:
    build: .
    ports:
      - "5003:5000"
    volumes:
      - node3_data:/app/data

  node4:
    build: .
    ports:
      - "5004:5000"
    volumes:
      - node4_data:/app/data

  node5:
    build: .
    ports:
      - "5005:5000"
    volumes:
      - node5_data:/app/data

  node6:
    build: .
    ports:
      - "5006:5000"
    volumes:
      - node6_data:/app/data

volumes:
  node1_data:
  node2_data:
  node3_data:
  node4_data:
  node5_data:
  node6_data:
