version: '3.8'

services:
  node1:
    build: .
    container_name: node1
    environment:
      - NODE_NAME=node1
      - HTTP_PORT=5001
    ports:
      - "5001:5000"
    volumes:
      - node1_data:/app/data

  node2:
    build: .
    container_name: node2
    environment:
      - NODE_NAME=node2
      - HTTP_PORT=5002
    ports:
      - "5002:5000"
    volumes:
      - node2_data:/app/data

  node3:
    build: .
    container_name: node3
    environment:
      - NODE_NAME=node3
      - HTTP_PORT=5003
    ports:
      - "5003:5000"
    volumes:
      - node3_data:/app/data

  node4:
    build: .
    container_name: node4
    environment:
      - NODE_NAME=node4
      - HTTP_PORT=5004
    ports:
      - "5004:5000"
    volumes:
      - node4_data:/app/data

  node5:
    build: .
    container_name: node5
    environment:
      - NODE_NAME=node5
      - HTTP_PORT=5005
    ports:
      - "5005:5000"
    volumes:
      - node5_data:/app/data

  node6:
    build: .
    container_name: node6
    environment:
      - NODE_NAME=node6
      - HTTP_PORT=5006
    ports:
      - "5006:5000"
    volumes:
      - node6_data:/app/data

volumes:
  node1_data:
  node2_data:
  node3_data:
  node4_data:
  node5_data:
  node6_data:
